#!<%= ENV['SHELL'] || '/bin/bash' %>
tmux start-server

tmux -u2 new-session -d -s <%= session_name %>

% data['windows'].each_with_index do |window, i|
  %= new_window(i, window.keys.first)
  % options = window.values.first

  % if options.is_a?(Hash)
    % options['panes'].each_with_index do |pane, j|
      %= create_pane if j > 0
      %= run_command i, pane
    % end
    %= select_layout(i, options['layout'])
  % else
    %= run_command(i, options)
  % end
% end

%= attach_session
