#!<%= ENV['SHELL'] || '/bin/bash' %>
tmux start-server

tmux -u2 new-session -d -s <%= session_name %>

% windows.each_with_index do |window, i|
  %= new_window(i, window.name)

  % if window.has_panes?
    % window.panes.each_with_index do |pane, j|
      %= create_pane if j > 0
      %= run_command i, pane.command
    % end
    %= select_layout(i, window.layout)
  % else
    %= run_command(i, window.options)
  % end
% end

%= attach_session
